## Copyright (c) 2011 The WebM project authors. All Rights Reserved.
## 
## Use of this source code is governed by a BSD-style license
## that can be found in the LICENSE file in the root of the source
## tree. An additional intellectual property rights grant can be found
## in the file PATENTS.  All contributing project authors may
## be found in the AUTHORS file in the root of the source tree.
# This file automatically generated by configure. Do not edit!
TOOLCHAIN := aarch64-linux-android31
ALL_TARGETS += libs
ALL_TARGETS += tools

PREFIX=/usr/local
ifeq ($(MAKECMDGOALS),dist)
DIST_DIR?=vpx-vp9-nodocs-aarch64-linux-v1.7.0
else
DIST_DIR?=$(DESTDIR)/usr/local
endif
LIBSUBDIR=lib

VERSION_STRING=v1.7.0

VERSION_MAJOR=1
VERSION_MINOR=7
VERSION_PATCH=0

CONFIGURE_ARGS=--force-target=aarch64-linux-android31 --sdk-path=/root/android-ndk-r26c --enable-neon --enable-internal-stats --disable-examples --disable-docs --enable-realtime-only --disable-vp8 --enable-libyuv --disable-runtime-cpu-detect --enable-snpe --extra-cflags=-isystem /root/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
CONFIGURE_ARGS?=--force-target=aarch64-linux-android31 --sdk-path=/root/android-ndk-r26c --enable-neon --enable-internal-stats --disable-examples --disable-docs --enable-realtime-only --disable-vp8 --enable-libyuv --disable-runtime-cpu-detect --enable-snpe --extra-cflags=-isystem /root/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
