## Copyright (c) 2011 The WebM project authors. All Rights Reserved.
## 
## Use of this source code is governed by a BSD-style license
## that can be found in the LICENSE file in the root of the source
## tree. An additional intellectual property rights grant can be found
## in the file PATENTS.  All contributing project authors may
## be found in the AUTHORS file in the root of the source tree.
# This file automatically generated by configure. Do not edit!
SRC_PATH="../../libvpx"
SRC_PATH_BARE=../../libvpx
BUILD_PFX=
TOOLCHAIN=aarch64-linux-android31
ASM_CONVERSION=../../libvpx/build/make/ads2gas.pl
GEN_VCPROJ=
MSVS_ARCH_DIR=

CC=/root/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android31-clang
CXX=/root/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android31-clang++
AR=
LD=/root/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android31-clang++
AS=
STRIP=
NM=

CFLAGS  =  -DNDEBUG -O3 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -isystem /root/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
CXXFLAGS  =  -DNDEBUG -O3 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -isystem /root/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
ARFLAGS = -crs$(if $(quiet),,v)
LDFLAGS = 
ASFLAGS = 
extralibs =  -pthread
AS_SFX    = .asm
EXE_SFX   = 
VCPROJ_SFX = 
RTCD_OPTIONS = 
fmt_deps = sed -e 's;^\([a-zA-Z0-9_]*\)\.o;${@:.d=.o} $@;'
HAVE_NEON=yes
HAVE_VPX_PORTS=yes
HAVE_PTHREAD_H=yes
HAVE_UNISTD_H=yes
CONFIG_DEPENDENCY_TRACKING=yes
CONFIG_INSTALL_BINS=yes
CONFIG_INSTALL_LIBS=yes
CONFIG_VP9_POSTPROC=yes
CONFIG_MULTITHREAD=yes
CONFIG_INTERNAL_STATS=yes
CONFIG_VP9_ENCODER=yes
CONFIG_VP9_DECODER=yes
CONFIG_VP9=yes
CONFIG_ENCODERS=yes
CONFIG_DECODERS=yes
CONFIG_SPATIAL_RESAMPLING=yes
CONFIG_REALTIME_ONLY=yes
CONFIG_STATIC=yes
CONFIG_OS_SUPPORT=yes
CONFIG_UNIT_TESTS=yes
CONFIG_WEBM_IO=yes
CONFIG_LIBYUV=yes
CONFIG_TEMPORAL_DENOISING=yes
CONFIG_SNPE=yes
